### ISSUE TITLE
Directory.Move not working over volumes with CopyAllowed

### ISSUE THREAD

**Issue by frontier777** [alphaleonis/AlphaFS#256]
Using .NET 3.5 and the 3.5 lib from AlphaFS.2.0.1.zip
DIrectory.Move across volumes is not working even with the CopyAllowed option set.

eg.

```
Dim l_SourceFolderPath As String = "C:\Temp\Test1"
Dim l_TargetFolderPath As String = "E:\Temp\Test2"

Alphaleonis.Win32.Filesystem.Directory.Move( _
  l_SourceFolderPath, _
  l_TargetFolderPath, _
  Alphaleonis.Win32.Filesystem.MoveOptions.CopyAllowed)
```

This fails with the following exception:

System.UnauthorizedAccessException occurred
  Message=(5) Access is denied: [\?\E:\Temp\Test2]
  Source=AlphaFS
  StackTrace:
       at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath) in d:\Coding\Projects\GitHub\AlphaFS\AlphaFS\NativeError.cs:line 102
  InnerException: 

Directory Copy and Delete works fine, so it is not a permission issue with either of the folders.

```
Alphaleonis.Win32.Filesystem.Directory.Copy( _
  l_SourceFolderPath, _
  l_TargetFolderPath)

Alphaleonis.Win32.Filesystem.Directory.Delete( _
  l_SourceFolderPath, _
  True)
```

I assumed this is what the MoveOptions.CopyAllowed option was supposed to do?

**Comment by Yomodo** [comment]
Yes, `MoveOptions.CopyAllowed` should enable moving across volumes.

Are there any read-only folders/files that are moved?

**Comment by frontier777** [comment]
There are 3 files and no sub-folders in Test1 and none are read-only. (checked each one)

Also AlphaFS Copy and then then Delete work fine, as per my last example, so to me that seems to rule out any permission or read-only issues.

Forgot to mention above, I'm using Windows 7 x64, but also see the problem on Windows Server 2012 R2.

**Comment by Yomodo** [comment]
Could you also test with the latest development build? (2.1.0.0)

**Comment by frontier777** [comment]
Yes happy to test, but not sure where to find it? I will need a binary as I only have VS2010 installed and can't build from source.

**Comment by Yomodo** [comment]
Please find it here: https://github.com/alphaleonis/AlphaFS
I've uploaded two compiled AlphaFS.dll zip files for .NET 3.5 and .NET 4.0

**Comment by frontier777** [comment]
Thanks, I just tested with the .NET 3.5 version and get the same error. I'll test with the .NET 4 version tomorrow and let you know if any difference.

For referece I used:
https://github.com/alphaleonis/AlphaFS/blob/develop/AlphaFS-NET35.zip

**Comment by frontier777** [comment]
Tested with the  .NET 4 version now and get the same error.
It seems like it is trying to move, instead of copy+delete as per the option.

**Comment by Yomodo** [comment]
I've updated the two .DLL's, would you care to test again to make sure it is fixed?

**Comment by frontier777** [comment]
Tested with the .NET 3.5 version and issue remains. The dll is from about 2 hours ago as I write this, file size is 321,024 bytes.

**Comment by frontier777** [comment]
Tested with the .NET 4.0 version and the issue is solved. Same time stamp as above, file size is 293,888 bytes.

**Comment by Yomodo** [comment]
Hm.. seems I did something wrong with the .NET 3.5 dll.
Since the code is the same for .NET 3.5 and .NET 4.0 we can regard it as resolved.
